version: 2
build:
  os: "ubuntu-24.04"
  tools:
    python: "miniconda-latest"
sphinx:
  configuration: docs/conf.py
formats: all
conda:
  environment: opty-dev-env.yml
python:
  install:
    - method: setuptools
      path: .
